### ISSUE TITLE
点击start.bat无反应

### ISSUE THREAD

**Issue by murazi** [atrandys/trojan#3]
将trojan.exe设置为“以管理员方式打开”后可以启动，但会提示

`[2019-12-23 21:44:33] [WARN] trojan service (client) started at 127.0.0.1:8082`

服务端安装正常

其中8082是我浏览器设置的本地端口

**Comment by wgjwillis** [comment]
你需要把client里面的config.json文件    "local_port": 修改了。
运行bat以后，任务管理能看见。

**Comment by yyuurrii34** [comment]
> 你需要把client里面的config.json文件 "local_port": 修改了。
> 运行bat以后，任务管理能看见。

答非所问，楼主上传的记录已提示端口已修改。

楼主的问题，只要用记事本打开start.bat看下就明白，就两行，一行是提升管理员，二行是start /b trojan.exe -c config.conf
要么是第一行的问题，要么是第二行的问题。
第一行是可能出问题的：因为有些机器用这种vbscript方法提升管理员后，传递给管理员权限的窗口路径自动变成了c:\windows\system32，这个问题，建议你找找作者，看有没有别的脚本来提升管理员（当然我是知道的，但是我不想告诉你，麻烦）。
第二行也是可能出问题的：由于作者用了个start /b静默模式，为了方便，建议你改成start /min最小化模式，这样**首先解决了你说的没反应的问题**（话说，像你这种菜鸟是怎么混进来的），后面的trojan -c config.conf是trojan的参数格式，-c表示引用哪个配置文件，所以**要确保-c后面的文件名与文件夹中的配置文件名一致**，（当-c参数缺省时，默认使用config.conf作配置文件）

**Comment by huangzhuohua** [comment]
也不是说无反应吧，一闪而过，其实服务已经启动了

**Comment by murazi** [comment]
已经好久不用trojan了，关闭，好评~
